// kernels-b64.js — GENERATED by scripts/wasm-inline.mjs from kernels.wasm.
// Do not edit by hand ; run `npm run build:wasm` to regenerate.
/** Base64 of src/wasm/kernels.wasm — decoded + instantiated by igc-kernels.wasm.js. */
export default "AGFzbQEAAAABCwJgA39/fwBgAAF/AwMCAAEFAwEAAAcjAwtzY3JhdGNoQmFzZQABCHl1dlRvUkdCAAAGbWVtb3J5AgAK5wEC3gEBCX8gACABQQF0aiEGIAAgAUECdGohByAAIAFBBmxqIQgDQCABIANKBEAgBiADQQF0IglqLgEAIQogCCAJai4BACEEIAIgA0ECdGoiBUH/ASAKIAAgCWouAQAgByAJai4BACILIApqQQRtayIKaiIJIAlB/wFKG0EAIAlBAE4bOgAAIAVB/wEgCiAKQf8BShtBACAKQQBOGzoAASAFQf8BIAogC2oiCSAJQf8BShtBACAJQQBOGzoAAiAFQf8BIAQgBEH/AUobQQAgBEEAThs6AAMgA0EBaiEDDAELCwsFAEGACAs=";
