// wasm-inline.mjs — emit src/wasm/kernels-b64.js from src/wasm/kernels.wasm.
//
// Run by `npm run build:wasm` right after `asc`. The base64 module is what the
// WASM dist variant inlines (imported by src/igc-kernels.wasm.js), so the
// shipped `dist/granny-ro.wasm.esm.js` carries the kernel bytes with zero
// network fetch. Committed alongside kernels.wasm so `npm run build` (and the
// wasm seam in raw src) needs no wasm toolchain.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WASM = resolve(HERE, '..', 'src/wasm/kernels.wasm');
const OUT = resolve(HERE, '..', 'src/wasm/kernels-b64.js');

const b64 = readFileSync(WASM).toString('base64');
writeFileSync(
    OUT,
    '// kernels-b64.js — GENERATED by scripts/wasm-inline.mjs from kernels.wasm.\n' +
        '// Do not edit by hand ; run `npm run build:wasm` to regenerate.\n' +
        '/** Base64 of src/wasm/kernels.wasm — decoded + instantiated by igc-kernels.wasm.js. */\n' +
        `export default ${JSON.stringify(b64)};\n`,
);
console.log(`src/wasm/kernels-b64.js written (${b64.length} b64 chars).`);
